#服务器配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#spring数据库配置    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuyy
    username: root
    password: 123456
    
#mybatis配置
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations: classpath:/